version: "3.0"
services:
  catalogdb:
    image: mongo
    restart: always
    container_name: "catalog-mongo"
    expose:
      - 27017
  catalog:
    build:
        dockerfile: ./src/Catalog/Microservices.Catalog.Api/Dockerfile
        context: .
    container_name: "catalog-app"
    depends_on:
      - catalogdb
    ports:
      - "8080:80" 
  basketdb:
    image: redis
    restart: always
    container_name: "basket-redis"
    expose:
      - 6379
  basket:
    build: 
        dockerfile: ./src/Basket/Microservices.Basket.Api/Dockerfile
        context: .
    container_name: "basket-app"
    depends_on:
      - basketdb
    ports:
      - "9090:80" 

  discountdb:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword

  discount:
    build: 
        dockerfile: ./src/Discount/Microservices.Discount.Api/Dockerfile
        context: .
    container_name: "discount-app"
    depends_on:
      - discountdb
    ports:
      - "9091:80" 

  discount-grpc:
    build: 
        dockerfile: ./src/Discount/Microservices.Discount.Grpc/Dockerfile
        context: .
    container_name: "discount-app-grpc"
    depends_on:
      - discountdb
    expose:
      - 80
    ports:
      - "9093:80" 

volumes:
  postgres_data: